#ifndef SRC_ERRLIST_H_
#define SRC_ERRLIST_H_

#define MAC_ERRLIST                                                            \
  {                                                                            \
    errlist[0] = "Undefined error: 0";                                         \
    errlist[1] = "Operation not permitted";                                    \
    errlist[2] = "No such file or directory";                                  \
    errlist[3] = "No such process";                                            \
    errlist[4] = "Interrupted system call";                                    \
    errlist[5] = "Input/output error";                                         \
    errlist[6] = "Device not configured";                                      \
    errlist[7] = "Argument list too long";                                     \
    errlist[8] = "Exec format error";                                          \
    errlist[9] = "Bad file descriptor";                                        \
    errlist[10] = "No child processes";                                        \
    errlist[11] = "Resource deadlock avoided";                                 \
    errlist[12] = "Cannot allocate memory";                                    \
    errlist[13] = "Permission denied";                                         \
    errlist[14] = "Bad address";                                               \
    errlist[15] = "Block device required";                                     \
    errlist[16] = "Resource busy";                                             \
    errlist[17] = "File exists";                                               \
    errlist[18] = "Cross-device link";                                         \
    errlist[19] = "Operation not supported by device";                         \
    errlist[20] = "Not a directory";                                           \
    errlist[21] = "Is a directory";                                            \
    errlist[22] = "Invalid argument";                                          \
    errlist[23] = "Too many open files in system";                             \
    errlist[24] = "Too many open files";                                       \
    errlist[25] = "Inappropriate ioctl for device";                            \
    errlist[26] = "Text file busy";                                            \
    errlist[27] = "File too large";                                            \
    errlist[28] = "No space left on device";                                   \
    errlist[29] = "Illegal seek";                                              \
    errlist[30] = "Read-only file system";                                     \
    errlist[31] = "Too many links";                                            \
    errlist[32] = "Broken pipe";                                               \
    errlist[33] = "Numerical argument out of domain";                          \
    errlist[34] = "Result too large";                                          \
    errlist[35] = "Resource temporarily unavailable";                          \
    errlist[36] = "Operation now in progress";                                 \
    errlist[37] = "Operation already in progress";                             \
    errlist[38] = "Socket operation on non-socket";                            \
    errlist[39] = "Destination address required";                              \
    errlist[40] = "Message too long";                                          \
    errlist[41] = "Protocol wrong type for socket";                            \
    errlist[42] = "Protocol not available";                                    \
    errlist[43] = "Protocol not supported";                                    \
    errlist[44] = "Socket type not supported";                                 \
    errlist[45] = "Operation not supported";                                   \
    errlist[46] = "Protocol family not supported";                             \
    errlist[47] = "Address family not supported by protocol family";           \
    errlist[48] = "Address already in use";                                    \
    errlist[49] = "Can't assign requested address";                            \
    errlist[50] = "Network is down";                                           \
    errlist[51] = "Network is unreachable";                                    \
    errlist[52] = "Network dropped connection on reset";                       \
    errlist[53] = "Software caused connection abort";                          \
    errlist[54] = "Connection reset by peer";                                  \
    errlist[55] = "No buffer space available";                                 \
    errlist[56] = "Socket is already connected";                               \
    errlist[57] = "Socket is not connected";                                   \
    errlist[58] = "Can't send after socket shutdown";                          \
    errlist[59] = "Too many references = can't splice";                        \
    errlist[60] = "Operation timed out";                                       \
    errlist[61] = "Connection refused";                                        \
    errlist[62] = "Too many levels of symbolic links";                         \
    errlist[63] = "File name too long";                                        \
    errlist[64] = "Host is down";                                              \
    errlist[65] = "No route to host";                                          \
    errlist[66] = "Directory not empty";                                       \
    errlist[67] = "Too many processes";                                        \
    errlist[68] = "Too many users";                                            \
    errlist[69] = "Disc quota exceeded";                                       \
    errlist[70] = "Stale NFS file handle";                                     \
    errlist[71] = "Too many levels of remote in path";                         \
    errlist[72] = "RPC struct is bad";                                         \
    errlist[73] = "RPC version wrong";                                         \
    errlist[74] = "RPC prog. not avail";                                       \
    errlist[75] = "Program version wrong";                                     \
    errlist[76] = "Bad procedure for program";                                 \
    errlist[77] = "No locks available";                                        \
    errlist[78] = "Function not implemented";                                  \
    errlist[79] = "Inappropriate file type or format";                         \
    errlist[80] = "Authentication error";                                      \
    errlist[81] = "Need authenticator";                                        \
    errlist[82] = "Device power is off";                                       \
    errlist[83] = "Device error";                                              \
    errlist[84] = "Value too large to be stored in data type";                 \
    errlist[85] = "Bad executable (or shared library)";                        \
    errlist[86] = "Bad CPU type in executable";                                \
    errlist[87] = "Shared library version mismatch";                           \
    errlist[88] = "Malformed Mach-o file";                                     \
    errlist[89] = "Operation canceled";                                        \
    errlist[90] = "Identifier removed";                                        \
    errlist[91] = "No message of desired type";                                \
    errlist[92] = "Illegal byte sequence";                                     \
    errlist[93] = "Attribute not found";                                       \
    errlist[94] = "Bad message";                                               \
    errlist[95] = "EMULTIHOP (Reserved)";                                      \
    errlist[96] = "No message available on STREAM";                            \
    errlist[97] = "ENOLINK (Reserved)";                                        \
    errlist[98] = "No STREAM resources";                                       \
    errlist[99] = "Not a STREAM";                                              \
    errlist[100] = "Protocol error";                                           \
    errlist[101] = "STREAM ioctl timeout";                                     \
    errlist[102] = "Operation not supported on socket";                        \
    errlist[103] = "Policy not found";                                         \
    errlist[104] = "State not recoverable";                                    \
    errlist[105] = "Previous owner died";                                      \
    errlist[106] = "Interface output queue is full";                           \
  }

#define LIN_ERRLIST                                                            \
  {                                                                            \
    errlist[0] = "Success";                                                    \
    errlist[1] = "Operation not permitted";                                    \
    errlist[2] = "No such file or directory";                                  \
    errlist[3] = "No such process";                                            \
    errlist[4] = "Interrupted system call";                                    \
    errlist[5] = "Input/output error";                                         \
    errlist[6] = "No such device or address";                                  \
    errlist[7] = "Argument list too long";                                     \
    errlist[8] = "Exec format error";                                          \
    errlist[9] = "Bad file descriptor";                                        \
    errlist[10] = "No child processes";                                        \
    errlist[11] = "Resource temporarily unavailable";                          \
    errlist[12] = "Cannot allocate memory";                                    \
    errlist[13] = "Permission denied";                                         \
    errlist[14] = "Bad address";                                               \
    errlist[15] = "Block device required";                                     \
    errlist[16] = "Device or resource busy";                                   \
    errlist[17] = "File exists";                                               \
    errlist[18] = "Invalid cross-device link";                                 \
    errlist[19] = "No such device";                                            \
    errlist[20] = "Not a directory";                                           \
    errlist[21] = "Is a directory";                                            \
    errlist[22] = "Invalid argument";                                          \
    errlist[23] = "Too many open files in system";                             \
    errlist[24] = "Too many open files";                                       \
    errlist[25] = "Inappropriate ioctl for device";                            \
    errlist[26] = "Text file busy";                                            \
    errlist[27] = "File too large";                                            \
    errlist[28] = "No space left on device";                                   \
    errlist[29] = "Illegal seek";                                              \
    errlist[30] = "Read-only file system";                                     \
    errlist[31] = "Too many links";                                            \
    errlist[32] = "Broken pipe";                                               \
    errlist[33] = "Numerical argument out of domain";                          \
    errlist[34] = "Numerical result out of range";                             \
    errlist[35] = "Resource deadlock avoided";                                 \
    errlist[36] = "File name too long";                                        \
    errlist[37] = "No locks available";                                        \
    errlist[38] = "Function not implemented";                                  \
    errlist[39] = "Directory not empty";                                       \
    errlist[40] = "Too many levels of symbolic links";                         \
    errlist[41] = "Unknown error 41";                                          \
    errlist[42] = "No message of desired type";                                \
    errlist[43] = "Identifier removed";                                        \
    errlist[44] = "Channel number out of range";                               \
    errlist[45] = "Level 2 not synchronized";                                  \
    errlist[46] = "Level 3 halted";                                            \
    errlist[47] = "Level 3 reset";                                             \
    errlist[48] = "Link number out of range";                                  \
    errlist[49] = "Protocol driver not attached";                              \
    errlist[50] = "No CSI structure available";                                \
    errlist[51] = "Level 2 halted";                                            \
    errlist[52] = "Invalid exchange";                                          \
    errlist[53] = "Invalid request descriptor";                                \
    errlist[54] = "Exchange full";                                             \
    errlist[55] = "No anode";                                                  \
    errlist[56] = "Invalid request code";                                      \
    errlist[57] = "Invalid slot";                                              \
    errlist[58] = "Unknown error 58";                                          \
    errlist[59] = "Bad font file format";                                      \
    errlist[60] = "Device not a stream";                                       \
    errlist[61] = "No data available";                                         \
    errlist[62] = "Timer expired";                                             \
    errlist[63] = "Out of streams resources";                                  \
    errlist[64] = "Machine is not on the network";                             \
    errlist[65] = "Package not installed";                                     \
    errlist[66] = "Object is remote";                                          \
    errlist[67] = "Link has been severed";                                     \
    errlist[68] = "Advertise error";                                           \
    errlist[69] = "Srmount error";                                             \
    errlist[70] = "Communication error on send";                               \
    errlist[71] = "Protocol error";                                            \
    errlist[72] = "Multihop attempted";                                        \
    errlist[73] = "RFS specific error";                                        \
    errlist[74] = "Bad message";                                               \
    errlist[75] = "Value too large for defined data type";                     \
    errlist[76] = "Name not unique on network";                                \
    errlist[77] = "File descriptor in bad state";                              \
    errlist[78] = "Remote address changed";                                    \
    errlist[79] = "Can not access a needed shared library";                    \
    errlist[80] = "Accessing a corrupted shared library";                      \
    errlist[81] = ".lib section in a.out corrupted";                           \
    errlist[82] = "Attempting to link in too many shared libraries";           \
    errlist[83] = "Cannot exec a shared library directly";                     \
    errlist[84] = "Invalid or incomplete multibyte or wide character";         \
    errlist[85] = "Interrupted system call should be restarted";               \
    errlist[86] = "Streams pipe error";                                        \
    errlist[87] = "Too many users";                                            \
    errlist[88] = "Socket operation on non-socket";                            \
    errlist[89] = "Destination address required";                              \
    errlist[90] = "Message too long";                                          \
    errlist[91] = "Protocol wrong type for socket";                            \
    errlist[92] = "Protocol not available";                                    \
    errlist[93] = "Protocol not supported";                                    \
    errlist[94] = "Socket type not supported";                                 \
    errlist[95] = "Operation not supported";                                   \
    errlist[96] = "Protocol family not supported";                             \
    errlist[97] = "Address family not supported by protocol";                  \
    errlist[98] = "Address already in use";                                    \
    errlist[99] = "Cannot assign requested address";                           \
    errlist[100] = "Network is down";                                          \
    errlist[101] = "Network is unreachable";                                   \
    errlist[102] = "Network dropped connection on reset";                      \
    errlist[103] = "Software caused connection abort";                         \
    errlist[104] = "Connection reset by peer";                                 \
    errlist[105] = "No buffer space available";                                \
    errlist[106] = "Transport endpoint is already connected";                  \
    errlist[107] = "Transport endpoint is not connected";                      \
    errlist[108] = "Cannot send after transport endpoint shutdown";            \
    errlist[109] = "Too many references: cannot splice";                       \
    errlist[110] = "Connection timed out";                                     \
    errlist[111] = "Connection refused";                                       \
    errlist[112] = "Host is down";                                             \
    errlist[113] = "No route to host";                                         \
    errlist[114] = "Operation already in progress";                            \
    errlist[115] = "Operation now in progress";                                \
    errlist[116] = "Stale file handle";                                        \
    errlist[117] = "Structure needs cleaning";                                 \
    errlist[118] = "Not a XENIX named type file";                              \
    errlist[119] = "No XENIX semaphores available";                            \
    errlist[120] = "Is a named type file";                                     \
    errlist[121] = "Remote I/O error";                                         \
    errlist[122] = "Disk quota exceeded";                                      \
    errlist[123] = "No medium found";                                          \
    errlist[124] = "Wrong medium type";                                        \
    errlist[125] = "Operation canceled";                                       \
    errlist[126] = "Required key not available";                               \
    errlist[127] = "Key has expired";                                          \
    errlist[128] = "Key has been revoked";                                     \
    errlist[129] = "Key was rejected by service";                              \
    errlist[130] = "Owner died";                                               \
    errlist[131] = "State not recoverable";                                    \
    errlist[132] = "Operation not possible due to RF-kill";                    \
    errlist[133] = "Memory page has hardware error";                           \
  }

#endif // SRC_ERRLIST_H_
